'use client';

import { generateConversationTitle } from '@/client/services/titleService';

import { DEFAULT_ANALYSIS_MODEL } from '@/lib/utils/app/const';

import { ConversationEntry, Message, MessageType } from '@/types/chat';

import { useConversationStore } from '@/client/stores/conversationStore';
import { v4 as uuidv4 } from 'uuid';

/** Longest instant fallback title, matching chatStore.generateConversationName. */
const FALLBACK_MAX = 50;
/** Cap on the content sample sent to the titler. */
const SAMPLE_MAX = 2000;

export interface WorkflowTitleSeed {
  /**
   * Human-meaningful name for what was just added — a filename, a search
   * query, a pasted-data label. Used verbatim as the instant title when it
   * already reads like one.
   */
  label?: string;
  /**
   * The content itself (source text, extracted rows, document body). Drives
   * the AI title, and provides the instant title when there is no label.
   */
  sample?: string;
  /** Workflow name, e.g. "Translation" — context for the titler. */
  workflow: string;
}

/**
 * Names a workflow conversation from the first content the user puts into
 * it, mirroring how chat names itself from the first message: an instant
 * truncation, then a written title that replaces it a moment later.
 *
 * Workflows need their own entry point because their content never passes
 * through `finalizeMessage` — a translation or an imported table isn't a
 * chat turn, so nothing was naming those conversations at all.
 *
 * Safe to call on every content-adding action: it no-ops once the
 * conversation carries a user-chosen name.
 */
export function nameWorkflowConversation(
  conversationId: string,
  seed: WorkflowTitleSeed,
): void {
  const store = useConversationStore.getState();
  const conversation = store.conversations.find((c) => c.id === conversationId);
  if (!conversation) return;

  // Absent nameAutoGenerated on a named conversation means the user named
  // it (or it predates the field) — either way, leave it alone.
  const isUntitled =
    conversation.name === '' || conversation.name === 'New Conversation';
  if (!isUntitled && !conversation.nameAutoGenerated) return;

  // A label is title-shaped and authoritative (a filename, a document's own
  // heading), so it may upgrade an earlier auto-name. A sample-derived
  // truncation may not: once a translation is named for the file it came
  // from, running it must not demote that to the first line of the text.
  const fallback = buildFallbackTitle(seed);
  const mayWriteFallback = isUntitled || Boolean(seed.label?.trim());
  if (fallback && mayWriteFallback && conversation.name !== fallback) {
    store.updateConversation(conversationId, {
      name: fallback,
      nameAutoGenerated: true,
    });
  }

  const sample = seed.sample?.trim();
  if (!sample) return;

  const modelId = conversation.model?.id || DEFAULT_ANALYSIS_MODEL;
  generateConversationTitle(syntheticEntries(seed, sample), modelId)
    .then((result) => {
      if (!result?.title) return;
      // Re-read: the user may have renamed the conversation during the
      // round trip, and a background titler must never clobber that.
      const latest = useConversationStore
        .getState()
        .conversations.find((c) => c.id === conversationId);
      if (!latest || !latest.nameAutoGenerated) return;
      useConversationStore.getState().updateConversation(conversationId, {
        name: result.title,
        nameAutoGenerated: true,
      });
    })
    .catch((error) => {
      console.error('[WorkflowTitle] Failed to generate AI title:', error);
    });
}

function buildFallbackTitle(seed: WorkflowTitleSeed): string {
  // A filename or a search query is already title-shaped; use it as-is.
  if (seed.label?.trim()) return truncate(seed.label.trim());
  const firstLine = seed.sample?.trim().split('\n')[0]?.trim();
  return firstLine ? truncate(firstLine) : '';
}

function truncate(value: string): string {
  return value.length > FALLBACK_MAX
    ? `${value.slice(0, FALLBACK_MAX)}...`
    : value;
}

/**
 * The title route is message-shaped, so workflow content is wrapped in a
 * single synthetic user turn. Never appended to the conversation — this
 * exists only for the duration of the title request.
 */
function syntheticEntries(
  seed: WorkflowTitleSeed,
  sample: string,
): ConversationEntry[] {
  const parts = [`${seed.workflow} workflow.`];
  if (seed.label?.trim()) parts.push(`Source: ${seed.label.trim()}`);
  parts.push(sample.slice(0, SAMPLE_MAX));

  const message: Message = {
    id: uuidv4(),
    role: 'user',
    content: parts.join('\n'),
    messageType: MessageType.TEXT,
  };
  return [message];
}
