import reactPlugin from 'eslint-plugin-react';
import hooksPlugin from 'eslint-plugin-react-hooks';

import js from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';

export default [
  js.configs.recommended,
  {
    ignores: [
      '.next/**/*',
      'node_modules/**/*',
      'coverage/**/*',
      '*.config.js',
      '*.config.mjs',
      '.husky/**/*',
    ],
  },
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        BroadcastChannel: 'readonly',
        MessageEvent: 'readonly',
        crypto: 'readonly',
        CryptoKey: 'readonly',
        indexedDB: 'readonly',
        IDBDatabase: 'readonly',
        IDBObjectStore: 'readonly',
        IDBRequest: 'readonly',
        IDBTransactionMode: 'readonly',
        Audio: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        FormData: 'readonly',
        File: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        ReadableStream: 'readonly',
        TransformStream: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        // DOM types
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLOptionElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLAudioElement: 'readonly',
        SVGSVGElement: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        ClipboardEvent: 'readonly',
        Event: 'readonly',
        EventTarget: 'readonly',
        EventListener: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        Window: 'readonly',
        Navigator: 'readonly',
        FileList: 'readonly',
        FileReader: 'readonly',
        DataTransfer: 'readonly',
        Image: 'readonly',
        HTMLImageElement: 'readonly',
        ImageBitmap: 'readonly',
        CanvasImageSource: 'readonly',
        MediaStream: 'readonly',
        MediaRecorder: 'readonly',
        MediaRecorderOptions: 'readonly',
        MediaStreamAudioSourceNode: 'readonly',
        MediaDeviceInfo: 'readonly',
        AudioContext: 'readonly',
        AnalyserNode: 'readonly',
        DOMException: 'readonly',
        DOMRect: 'readonly',
        MutationObserver: 'readonly',
        RequestInit: 'readonly',
        HeadersInit: 'readonly',
        PermissionName: 'readonly',
        BlobPart: 'readonly',
        NodeJS: 'readonly',
        WebAssembly: 'readonly',
        Storage: 'readonly',
        ScrollBehavior: 'readonly',
        ReadableStreamDefaultController: 'readonly',
        TransformStreamDefaultController: 'readonly',
        // Browser APIs
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        queueMicrotask: 'readonly',
        XMLHttpRequest: 'readonly',
        createImageBitmap: 'readonly',
        // Node.js globals
        global: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        // Test globals (Vitest)
        vi: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        // Next.js/React globals
        React: 'readonly',
        JSX: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      react: reactPlugin,
      'react-hooks': hooksPlugin,
      '@next/next': nextPlugin,
    },
    rules: {
      ...typescript.configs.recommended.rules,
      ...reactPlugin.configs.recommended.rules,
      ...hooksPlugin.configs.recommended.rules,
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/no-unescaped-entities': 'off',
      'react/no-unknown-property': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/prefer-as-const': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    // `no-undef` can't see TypeScript type space, so every DOM *type* used in
    // an annotation (BlobCallback, MediaRecorderOptions, …) has to be hand-
    // added to the globals list above or it errors — a list that silently goes
    // stale as the DOM lib grows. tsc already resolves these, and CI runs
    // `tsc --noEmit`, so the rule is pure duplicate work on typed files.
    // This is the configuration typescript-eslint documents for exactly this.
    files: ['**/*.{ts,tsx}'],
    rules: {
      'no-undef': 'off',
    },
  },
];
