/**
 * Turn a normalised `ForeignConversation` into the app's `Conversation`.
 *
 * Ids are deterministic (`import-<source>-<sourceId>`) so the picker can mark
 * conversations that were imported before, and so importing the same file
 * twice does not silently duplicate. Assistant turns are written directly as
 * single-version `AssistantMessageGroup`s (the current persisted shape), with
 * the source timestamp as the version's `createdAt`.
 */
import {
  AssistantMessageGroup,
  Conversation,
  Message,
  MessageType,
} from '@/types/chat';
import { OpenAIModel } from '@/types/openai';

import { ForeignConversation, ForeignSource } from './types';

import { v4 as uuidv4 } from 'uuid';

export const MAX_IMPORTED_TITLE_LENGTH = 120;

export interface ForeignConversationDefaults {
  model: OpenAIModel;
  prompt: string;
  temperature: number;
  folderId?: string | null;
}

const sanitizeIdPart = (value: string): string =>
  value.replace(/[^A-Za-z0-9_-]/g, '_').slice(0, 80);

export const foreignConversationId = (
  source: ForeignSource,
  sourceId: string,
): string => `import-${source}-${sanitizeIdPart(sourceId)}`;

/** Fallback title: first user line, trimmed to a sidebar-friendly length. */
export const deriveTitle = (
  conversation: ForeignConversation,
  fallback: string,
): string => {
  const explicit = conversation.title.trim();
  if (explicit) return explicit.slice(0, MAX_IMPORTED_TITLE_LENGTH);
  const firstUser = conversation.turns.find((t) => t.role === 'user');
  const firstLine = firstUser?.text.split('\n').find((l) => l.trim()) ?? '';
  const candidate = firstLine.trim();
  return candidate ? candidate.slice(0, MAX_IMPORTED_TITLE_LENGTH) : fallback;
};

export const foreignToConversation = (
  conversation: ForeignConversation,
  defaults: ForeignConversationDefaults,
  fallbackTitle: string,
): Conversation => {
  const now = new Date().toISOString();
  const messages = conversation.turns.map((turn) => {
    if (turn.role === 'assistant') {
      const group: AssistantMessageGroup = {
        type: 'assistant_group',
        activeIndex: 0,
        versions: [
          {
            content: turn.text,
            messageType: MessageType.TEXT,
            createdAt: turn.createdAt ?? conversation.createdAt ?? now,
          },
        ],
      };
      return group;
    }
    const message: Message = {
      id: uuidv4(),
      role: 'user',
      content: turn.text,
      messageType: MessageType.TEXT,
    };
    return message;
  });

  return {
    id: foreignConversationId(conversation.source, conversation.sourceId),
    name: deriveTitle(conversation, fallbackTitle),
    // A title we carried over from the source must not be overwritten by the
    // background AI titler.
    nameAutoGenerated: false,
    messages,
    model: defaults.model,
    prompt: defaults.prompt,
    temperature: defaults.temperature,
    folderId: defaults.folderId ?? null,
    createdAt: conversation.createdAt ?? now,
    // Falls back to createdAt (not `now`) so the backup engine's last-writer-
    // wins merge does not treat a freshly imported old thread as newer than
    // a real edit made elsewhere.
    updatedAt: conversation.updatedAt ?? conversation.createdAt ?? now,
    activeFiles: [],
    activeFilesMaxCount: 10,
    activeFilesTokensUsed: 0,
  };
};
