/**
 * Code Interpreter Types
 *
 * Types for Azure AI Foundry Code Interpreter integration.
 * Code Interpreter enables agents to execute Python code in a sandboxed
 * environment for data analysis, chart generation, and iterative problem-solving.
 */

/**
 * Code Interpreter Mode Configuration
 *
 * Controls when Code Interpreter is triggered for chat requests.
 * Allows intelligent routing based on query intent rather than just file presence.
 */
export enum CodeInterpreterMode {
  /**
   * Never use Code Interpreter, even if files are present.
   * Use for summarization, explanation, or text-based analysis.
   */
  OFF = 'off',

  /**
   * AI intelligently decides when Code Interpreter is needed.
   * Analyzes query to determine if code execution is required:
   * - Data generation, transformation, analysis
   * - Chart/visualization creation
   * - File format conversion
   * Falls back to standard chat for summarization, explanation, etc.
   */
  INTELLIGENT = 'intelligent',

  /**
   * Always use Code Interpreter when compatible files are present.
   * Original behavior - file presence + compatibility triggers CI.
   */
  ALWAYS = 'always',
}

/**
 * Type guard for CodeInterpreterMode
 *
 * @param value - Value to check
 * @returns true if value is a valid CodeInterpreterMode
 */
export function isCodeInterpreterMode(
  value: unknown,
): value is CodeInterpreterMode {
  return Object.values(CodeInterpreterMode).includes(
    value as CodeInterpreterMode,
  );
}

/**
 * File uploaded to AI Foundry for Code Interpreter use.
 * Files are uploaded via the OpenAI files API with purpose='assistants'.
 */
export interface CodeInterpreterFile {
  /** AI Foundry file ID (assigned after upload) */
  id: string;

  /** Original filename */
  filename: string;

  /** File purpose - always 'assistants' for Code Interpreter */
  purpose: 'assistants';

  /** Container ID for file retrieval after execution */
  containerId?: string;

  /** MIME type of the file */
  mimeType?: string;

  /** File size in bytes */
  size?: number;
}

/**
 * Output generated by Code Interpreter execution.
 * Can be logs (Python print output), images (charts), or files (CSV, etc.).
 */
export interface CodeInterpreterOutput {
  /** Type of output */
  type: 'logs' | 'image' | 'file';

  /** For logs: Python print output / execution logs */
  content?: string;

  /** For generated files/images: AI Foundry file ID */
  fileId?: string;

  /** Generated filename */
  filename?: string;

  /** Container ID for file retrieval */
  containerId?: string;

  /** MIME type for inline rendering decisions */
  mimeType?: string;

  /** For images: base64 encoded data (when available inline) */
  base64Data?: string;

  /** For files: blob storage URL after persistence (if persisted) */
  blobUrl?: string;
}

/**
 * Metadata tracking Code Interpreter execution state.
 * Attached to messages for UI rendering and state tracking.
 */
export interface CodeInterpreterMetadata {
  /** Current phase of Code Interpreter execution */
  executionPhase: 'uploading' | 'executing' | 'completed' | 'error';

  /** All outputs generated during execution */
  outputs: CodeInterpreterOutput[];

  /** Files uploaded for this execution */
  uploadedFiles: CodeInterpreterFile[];

  /** Python code that was executed (for display) */
  code?: string;

  /** Error message if execution failed */
  error?: string;

  /** Execution duration in milliseconds */
  durationMs?: number;
}

/**
 * File types supported by Code Interpreter.
 * Based on Azure AI Foundry documentation.
 */
export const CODE_INTERPRETER_SUPPORTED_EXTENSIONS = [
  // Data files
  '.csv',
  '.xlsx',
  '.xls',
  '.json',
  '.xml',
  '.parquet',
  '.tsv',

  // Documents
  '.pdf',
  '.docx',
  '.doc',
  '.txt',
  '.md',
  '.rtf',

  // Images (for image processing/analysis)
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.bmp',

  // Code files
  '.py',
  '.ipynb',
  '.r',
  '.sql',

  // Archives (Code Interpreter can extract)
  '.zip',
] as const;

export type CodeInterpreterSupportedExtension =
  (typeof CODE_INTERPRETER_SUPPORTED_EXTENSIONS)[number];

/**
 * Checks if a file extension is supported by Code Interpreter.
 *
 * @param filename - The filename to check
 * @returns true if the file extension is supported
 */
export function isCodeInterpreterSupported(filename: string): boolean {
  const ext = filename.toLowerCase().slice(filename.lastIndexOf('.'));
  return CODE_INTERPRETER_SUPPORTED_EXTENSIONS.includes(
    ext as CodeInterpreterSupportedExtension,
  );
}

/**
 * Gets the MIME type for a Code Interpreter supported file.
 *
 * @param filename - The filename to get MIME type for
 * @returns MIME type string or undefined if not supported
 */
export function getCodeInterpreterMimeType(
  filename: string,
): string | undefined {
  const ext = filename.toLowerCase().slice(filename.lastIndexOf('.'));

  const mimeTypes: Record<string, string> = {
    // Data files
    '.csv': 'text/csv',
    '.xlsx':
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    '.xls': 'application/vnd.ms-excel',
    '.json': 'application/json',
    '.xml': 'application/xml',
    '.parquet': 'application/octet-stream',
    '.tsv': 'text/tab-separated-values',

    // Documents
    '.pdf': 'application/pdf',
    '.docx':
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    '.doc': 'application/msword',
    '.txt': 'text/plain',
    '.md': 'text/markdown',
    '.rtf': 'application/rtf',

    // Images
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
    '.bmp': 'image/bmp',

    // Code files
    '.py': 'text/x-python',
    '.ipynb': 'application/x-ipynb+json',
    '.r': 'text/x-r-source',
    '.sql': 'application/sql',

    // Archives
    '.zip': 'application/zip',
  };

  return mimeTypes[ext];
}
