'use client';

import {
  IconDownload,
  IconFile,
  IconFileSpreadsheet,
  IconLoader2,
  IconPhoto,
} from '@tabler/icons-react';
import React, { FC, useState } from 'react';

import { useTranslations } from 'next-intl';
import Image from 'next/image';

import { CodeInterpreterOutput } from '@/types/codeInterpreter';

/**
 * Props for GeneratedFilePreview component.
 */
interface GeneratedFilePreviewProps {
  /** Output from Code Interpreter */
  output: CodeInterpreterOutput;
}

/**
 * Preview and download component for files generated by Code Interpreter.
 *
 * Handles:
 * - Images: Inline preview with click-to-expand
 * - Data files (CSV, Excel): Download button with file icon
 * - Other files: Generic download button
 */
export const GeneratedFilePreview: FC<GeneratedFilePreviewProps> = ({
  output,
}) => {
  const t = useTranslations();
  const [isLoading, setIsLoading] = useState(false);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Determine file type icon
  const getFileIcon = () => {
    if (output.type === 'image') {
      return <IconPhoto size={20} className="text-blue-500" />;
    }

    const ext = output.filename?.split('.').pop()?.toLowerCase();
    if (ext === 'csv' || ext === 'xlsx' || ext === 'xls') {
      return <IconFileSpreadsheet size={20} className="text-green-500" />;
    }

    return <IconFile size={20} className="text-gray-500" />;
  };

  // Download the generated file
  const handleDownload = async () => {
    if (!output.fileId) return;

    setIsLoading(true);
    setError(null);

    try {
      const filename = output.filename || 'generated_file';
      const response = await fetch(
        `/api/file/generated/${output.fileId}?download=true&filename=${encodeURIComponent(filename)}`,
      );

      if (!response.ok) {
        throw new Error('Download failed');
      }

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);

      // Trigger download
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Download error:', err);
      setError(t('codeInterpreter.downloadFailed'));
    } finally {
      setIsLoading(false);
    }
  };

  // Load image preview
  const loadImagePreview = async () => {
    if (!output.fileId || imageUrl) return;

    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch(`/api/file/generated/${output.fileId}`);

      if (!response.ok) {
        throw new Error('Failed to load image');
      }

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      setImageUrl(url);
    } catch (err) {
      console.error('Image load error:', err);
      setError(t('codeInterpreter.imageLoadFailed'));
    } finally {
      setIsLoading(false);
    }
  };

  // For images, show inline preview
  if (output.type === 'image') {
    // If we have base64 data, display directly
    if (output.base64Data) {
      return (
        <div className="my-3">
          <Image
            src={`data:${output.mimeType || 'image/png'};base64,${output.base64Data}`}
            alt={output.filename || 'Generated image'}
            width={800}
            height={600}
            className="max-w-full h-auto rounded-lg border border-gray-200 dark:border-gray-700"
            unoptimized
          />
          <div className="flex items-center gap-2 mt-2">
            <button
              onClick={handleDownload}
              disabled={isLoading}
              className="flex items-center gap-1 text-sm text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
            >
              {isLoading ? (
                <IconLoader2 size={14} className="animate-spin" />
              ) : (
                <IconDownload size={14} />
              )}
              {t('common.download')}
            </button>
          </div>
        </div>
      );
    }

    // Otherwise, load from API
    if (!imageUrl && !error) {
      loadImagePreview();
    }

    return (
      <div className="my-3">
        {isLoading && (
          <div className="flex items-center justify-center h-32 bg-gray-100 dark:bg-gray-800 rounded-lg">
            <IconLoader2 size={24} className="animate-spin text-gray-400" />
          </div>
        )}

        {error && (
          <div className="flex items-center justify-center h-32 bg-red-50 dark:bg-red-900/20 rounded-lg">
            <span className="text-sm text-red-500">{error}</span>
          </div>
        )}

        {imageUrl && (
          <>
            <Image
              src={imageUrl}
              alt={output.filename || 'Generated image'}
              width={800}
              height={600}
              className="max-w-full h-auto rounded-lg border border-gray-200 dark:border-gray-700"
              unoptimized
            />
            <div className="flex items-center gap-2 mt-2">
              <button
                onClick={handleDownload}
                disabled={isLoading}
                className="flex items-center gap-1 text-sm text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
              >
                {isLoading ? (
                  <IconLoader2 size={14} className="animate-spin" />
                ) : (
                  <IconDownload size={14} />
                )}
                {t('common.download')}
              </button>
            </div>
          </>
        )}
      </div>
    );
  }

  // For files, show download button
  return (
    <div className="flex items-center gap-3 p-3 my-2 bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700">
      {getFileIcon()}

      <div className="flex-1 min-w-0">
        <span className="text-sm font-medium text-gray-700 dark:text-gray-300 truncate block">
          {output.filename || 'generated_file'}
        </span>
        <span className="text-xs text-gray-500 dark:text-gray-400">
          {t('codeInterpreter.generatedFile')}
        </span>
      </div>

      <button
        onClick={handleDownload}
        disabled={isLoading}
        className="flex items-center gap-1 px-3 py-1.5 text-sm bg-blue-500 hover:bg-blue-600 text-white rounded-md transition-colors disabled:opacity-50"
      >
        {isLoading ? (
          <IconLoader2 size={14} className="animate-spin" />
        ) : (
          <IconDownload size={14} />
        )}
        {t('common.download')}
      </button>

      {error && <span className="text-xs text-red-500">{error}</span>}
    </div>
  );
};

export default GeneratedFilePreview;
