import {
  deriveTitle,
  foreignConversationId,
  foreignToConversation,
} from '@/lib/utils/app/export/foreignImport/toConversation';
import { ForeignConversation } from '@/lib/utils/app/export/foreignImport/types';

import { isAssistantMessageGroup } from '@/types/chat';
import { OpenAIModelID, OpenAIModels } from '@/types/openai';

import { describe, expect, it } from 'vitest';

const foreign: ForeignConversation = {
  source: 'chatgpt',
  sourceId: 'abc/123 ?',
  title: '',
  createdAt: '2024-02-01T00:00:00.000Z',
  updatedAt: '2024-02-02T00:00:00.000Z',
  turns: [
    { role: 'user', text: 'First line here\nsecond line' },
    { role: 'assistant', text: 'Reply', createdAt: '2024-02-01T00:00:10.000Z' },
  ],
  droppedParts: 0,
};

const defaults = {
  model: OpenAIModels[OpenAIModelID.GPT_5_4],
  prompt: 'sys',
  temperature: 0.3,
  folderId: 'folder-1',
};

describe('toConversation', () => {
  it('derives deterministic, sanitised ids', () => {
    expect(foreignConversationId('chatgpt', 'abc/123 ?')).toBe(
      'import-chatgpt-abc_123__',
    );
    expect(foreignConversationId('claude', 'u-1')).toBe('import-claude-u-1');
  });

  it('uses the first user line as title when the source has none', () => {
    expect(deriveTitle(foreign, 'Untitled')).toBe('First line here');
    expect(
      deriveTitle({ ...foreign, title: '  Real title ' }, 'Untitled'),
    ).toBe('Real title');
    expect(deriveTitle({ ...foreign, turns: [] }, 'Untitled')).toBe('Untitled');
  });

  it('builds a Conversation with grouped assistant turns and source timestamps', () => {
    const conv = foreignToConversation(foreign, defaults, 'Untitled');
    expect(conv.id).toBe('import-chatgpt-abc_123__');
    expect(conv.model).toBe(defaults.model);
    expect(conv.prompt).toBe('sys');
    expect(conv.temperature).toBe(0.3);
    expect(conv.folderId).toBe('folder-1');
    expect(conv.nameAutoGenerated).toBe(false);
    expect(conv.createdAt).toBe('2024-02-01T00:00:00.000Z');
    expect(conv.updatedAt).toBe('2024-02-02T00:00:00.000Z');
    expect(conv.activeFiles).toEqual([]);

    expect(conv.messages).toHaveLength(2);
    const [user, assistant] = conv.messages;
    expect(isAssistantMessageGroup(user)).toBe(false);
    expect(user).toMatchObject({
      role: 'user',
      content: 'First line here\nsecond line',
    });
    expect(typeof (user as { id?: string }).id).toBe('string');
    expect(isAssistantMessageGroup(assistant)).toBe(true);
    if (isAssistantMessageGroup(assistant)) {
      expect(assistant.versions).toHaveLength(1);
      expect(assistant.versions[0].content).toBe('Reply');
      expect(assistant.versions[0].createdAt).toBe('2024-02-01T00:00:10.000Z');
    }
  });

  it('never stamps updatedAt newer than the source when timestamps are partial', () => {
    const conv = foreignToConversation(
      { ...foreign, updatedAt: undefined },
      defaults,
      'Untitled',
    );
    expect(conv.updatedAt).toBe(foreign.createdAt);
  });
});
