/**
 * Chat Title Generation API
 *
 * Generates a concise, descriptive title for a conversation using Azure OpenAI
 * with structured outputs (JSON schema).
 *
 * POST /api/chat/title
 * Body: { messages: Message[] }
 * Response: { title: string | null, fullTitle: string | null }
 * (title is null when generation failed — callers keep their local fallback)
 */
import { NextRequest, NextResponse } from 'next/server';

import { OPENAI_API_VERSION } from '@/lib/utils/app/const';

import {
  FileMessageContent,
  ImageMessageContent,
  Message,
  TextMessageContent,
} from '@/types/chat';
import { OpenAIModelID, OpenAIModels } from '@/types/openai';

import { auth } from '@/auth';
import {
  DefaultAzureCredential,
  getBearerTokenProvider,
} from '@azure/identity';
import { AzureOpenAI } from 'openai';

/**
 * Response type for the title generation.
 */
interface ChatTitleResponse {
  title: string;
}

/**
 * Titles are always generated by a small, cheap deployment — never the
 * conversation's own model. The conversation model may not be reachable
 * through this Azure OpenAI client at all (Claude via anthropic-foundry,
 * serverless DeepSeek/Llama/Mistral/Grok, byom-* sources, agent ids), and
 * routing by model id has to be kept in sync with every new source; a fixed
 * list can't drift.
 *
 * Ordered cheapest-first. Not every environment deploys every model (the EU
 * account carries only a few hand-created deployments), so on failure the
 * next candidate is tried; the last entry is the full model deployed in both
 * the US and EU accounts.
 */
const TITLE_MODEL_FALLBACKS: OpenAIModelID[] = [
  OpenAIModelID.GPT_5_4_NANO,
  OpenAIModelID.GPT_5_MINI,
  OpenAIModelID.GPT_5_4,
];

/**
 * Deployments that returned 404 (not deployed in this environment), remembered
 * per replica so later requests skip the wasted round trip.
 */
const deadDeployments = new Set<string>();

function isDeploymentNotFound(error: unknown): boolean {
  return (
    typeof error === 'object' &&
    error !== null &&
    (error as { status?: number }).status === 404
  );
}

/**
 * Filters messages to only include text content.
 * Removes file and image content to focus on textual information for title generation.
 */
function filterMessagesForTitleGeneration(messages: Message[]): Message[] {
  return messages.map((message) => {
    // Handle string content
    if (typeof message.content === 'string') {
      return message;
    }

    // Handle array content - filter to only include text content
    if (Array.isArray(message.content)) {
      const textContents = (
        message.content as (
          | TextMessageContent
          | FileMessageContent
          | ImageMessageContent
        )[]
      ).filter(
        (item: TextMessageContent | FileMessageContent | ImageMessageContent) =>
          item.type === 'text',
      ) as TextMessageContent[];

      return {
        ...message,
        content:
          textContents.length > 0 ? textContents : [{ type: 'text', text: '' }],
      };
    }

    // Handle object content - only include if it's text type
    if (typeof message.content === 'object' && message.content !== null) {
      if ((message.content as TextMessageContent).type === 'text') {
        return message;
      } else {
        // Replace non-text content with empty text
        return {
          ...message,
          content: { type: 'text', text: '' },
        };
      }
    }

    return message;
  });
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const body = await req.json();
    const { messages } = body as {
      messages: Message[];
      modelId?: string;
    };

    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return NextResponse.json(
        { error: 'No messages provided or invalid messages format' },
        { status: 400 },
      );
    }

    // Initialize Azure OpenAI client
    const scope = 'https://cognitiveservices.azure.com/.default';
    const azureADTokenProvider = getBearerTokenProvider(
      new DefaultAzureCredential(),
      scope,
    );

    // Prepare the system prompt for title generation
    const systemMessage = {
      role: 'system' as const,
      content: `Generate a concise, descriptive title for this conversation. The title should be less than 35 characters and should capture the main topic or purpose of the conversation. Use simple, direct language. Make it in whatever language the dominant conversation is in.`,
    };

    // Filter messages to only include text content
    const filteredMessages = filterMessagesForTitleGeneration(messages);

    // Define JSON schema for structured output
    const jsonSchema = {
      type: 'object' as const,
      properties: {
        title: {
          type: 'string' as const,
          description:
            'A concise title for the conversation (less than 35 characters)',
        },
      },
      required: ['title'] as const,
      additionalProperties: false,
    };

    const apiMessages = [
      systemMessage,
      ...filteredMessages.map((m) => ({
        role: m.role as 'user' | 'assistant' | 'system',
        content:
          typeof m.content === 'string'
            ? m.content
            : Array.isArray(m.content)
              ? m.content
                  .filter((c) => c.type === 'text')
                  .map((c) => (c as TextMessageContent).text)
                  .join('\n')
              : '',
      })),
    ];

    // Walk the fallback chain until one deployment produces a title. Empty
    // content (e.g. a reasoning-capable model spending its whole completion
    // budget on reasoning tokens) also advances to the next candidate.
    for (const deploymentId of TITLE_MODEL_FALLBACKS) {
      if (deadDeployments.has(deploymentId)) continue;

      try {
        const openai = new AzureOpenAI({
          azureADTokenProvider,
          deployment: deploymentId,
          apiVersion: OPENAI_API_VERSION,
        });

        // Check if model supports custom temperature (also indicates API
        // parameter format). The completion cap leaves headroom for
        // reasoning-capable models, which spend completion tokens on
        // reasoning before emitting the (tiny) JSON title.
        const supportsTemperature =
          OpenAIModels[deploymentId]?.supportsTemperature !== false;

        const response = await openai.chat.completions.create({
          model: deploymentId,
          messages: apiMessages,
          ...(supportsTemperature
            ? { temperature: 0.7, max_tokens: 100 }
            : { max_completion_tokens: 1000 }),
          response_format: {
            type: 'json_schema',
            json_schema: {
              name: 'title_response',
              strict: true,
              schema: jsonSchema,
            },
          },
        });

        const content = response.choices[0]?.message?.content;
        if (!content) {
          console.warn(
            `[Title Generation] Empty content from ${deploymentId}, trying next candidate`,
          );
          continue;
        }

        const titleResponse: ChatTitleResponse = JSON.parse(content);
        return NextResponse.json(
          {
            title: titleResponse.title.slice(0, 31),
            fullTitle: titleResponse.title,
          },
          { status: 200 },
        );
      } catch (error) {
        if (isDeploymentNotFound(error)) {
          // Not deployed in this environment — skip it for the lifetime of
          // this replica instead of paying the 404 on every title request.
          deadDeployments.add(deploymentId);
        }
        console.warn(
          `[Title Generation] ${deploymentId} failed, trying next candidate:`,
          error,
        );
      }
    }

    // All candidates failed. Title generation is non-essential — return a
    // null title rather than 500 so the chat UI keeps working. The title must
    // be null, not a placeholder string: a placeholder would be treated as a
    // real title by the client and overwrite its own (better)
    // truncated-first-message fallback.
    console.error('[Title Generation] All fallback deployments failed');
    return NextResponse.json({ title: null, fullTitle: null }, { status: 200 });
  } catch (error) {
    // Title generation is best-effort — a failure here must not break the chat.
    // Log and return a null title so the client keeps its local fallback name
    // (a placeholder string here would clobber it) and doesn't surface a 500.
    console.error('[Title Generation] Error:', error);
    return NextResponse.json({ title: null, fullTitle: null }, { status: 200 });
  }
}
