import { nameWorkflowConversation } from '@/client/services/workflows/workflowTitle';

import { Conversation } from '@/types/chat';

import { useConversationStore } from '@/client/stores/conversationStore';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const generateConversationTitle = vi.hoisted(() => vi.fn());

vi.mock('@/client/services/titleService', () => ({
  generateConversationTitle,
}));

const conversation = (overrides: Partial<Conversation> = {}): Conversation =>
  ({
    id: 'w1',
    name: '',
    messages: [],
    model: { id: 'gpt-4', name: 'GPT-4', maxLength: 4000, tokenLimit: 4000 },
    prompt: '',
    temperature: 0.7,
    folderId: null,
    ...overrides,
  }) as Conversation;

function setStore(c: Conversation) {
  useConversationStore.setState({
    conversations: [c],
    selectedConversationId: c.id,
    folders: [],
    searchTerm: '',
    isLoaded: true,
  });
}

const stored = () => useConversationStore.getState().conversations[0];

/** Lets the fire-and-forget title promise settle. */
const flush = () => new Promise((resolve) => setTimeout(resolve, 0));

describe('nameWorkflowConversation', () => {
  beforeEach(() => {
    generateConversationTitle.mockReset();
    generateConversationTitle.mockResolvedValue(null);
    setStore(conversation());
  });

  describe('instant fallback', () => {
    it('names an untitled conversation from the label', () => {
      nameWorkflowConversation('w1', {
        label: 'supply-memo.docx',
        workflow: 'Translation',
      });
      expect(stored().name).toBe('supply-memo.docx');
      expect(stored().nameAutoGenerated).toBe(true);
    });

    it('falls back to the first line of the sample when there is no label', () => {
      nameWorkflowConversation('w1', {
        sample: 'Wir haben die Lieferung erhalten\nzweite Zeile',
        workflow: 'Translation',
      });
      expect(stored().name).toBe('Wir haben die Lieferung erhalten');
    });

    it('truncates a long fallback', () => {
      nameWorkflowConversation('w1', {
        sample: 'x'.repeat(120),
        workflow: 'Map',
      });
      expect(stored().name).toHaveLength(53); // 50 + '...'
      expect(stored().name.endsWith('...')).toBe(true);
    });

    it('does nothing when the seed carries neither label nor sample', () => {
      nameWorkflowConversation('w1', { workflow: 'Map' });
      expect(stored().name).toBe('');
    });

    it('treats the legacy "New Conversation" name as untitled', () => {
      setStore(conversation({ name: 'New Conversation' }));
      nameWorkflowConversation('w1', { label: 'cases.csv', workflow: 'Data' });
      expect(stored().name).toBe('cases.csv');
    });
  });

  describe('respecting a user-chosen name', () => {
    it('leaves a manually named conversation alone', () => {
      setStore(conversation({ name: 'Q3 supply review' }));
      nameWorkflowConversation('w1', {
        label: 'supply-memo.docx',
        sample: 'text',
        workflow: 'Translation',
      });
      expect(stored().name).toBe('Q3 supply review');
      expect(generateConversationTitle).not.toHaveBeenCalled();
    });

    it('leaves a pre-existing name without the flag alone', () => {
      // Conversations named before nameAutoGenerated existed must not be
      // retitled retroactively.
      setStore(conversation({ name: 'Older conversation' }));
      nameWorkflowConversation('w1', { label: 'a.csv', workflow: 'Data' });
      expect(stored().name).toBe('Older conversation');
    });
  });

  describe('upgrading an auto-generated name', () => {
    it('lets an authoritative label replace an earlier auto name', () => {
      setStore(conversation({ name: 'ref.docx', nameAutoGenerated: true }));
      nameWorkflowConversation('w1', {
        label: 'Cholera Response Plan',
        workflow: 'Document',
      });
      expect(stored().name).toBe('Cholera Response Plan');
    });

    it('does not let a sample truncation demote an earlier auto name', () => {
      // A translation named for its source file must survive being run.
      setStore(conversation({ name: 'memo.docx', nameAutoGenerated: true }));
      nameWorkflowConversation('w1', {
        sample: 'Some body text that would make a worse title',
        workflow: 'Translation',
      });
      expect(stored().name).toBe('memo.docx');
    });
  });

  describe('AI title', () => {
    it('replaces the fallback with the generated title', async () => {
      generateConversationTitle.mockResolvedValue({
        title: 'French supply memo',
        fullTitle: 'French supply memo translation',
      });
      nameWorkflowConversation('w1', {
        label: 'supply-memo.docx',
        sample: 'Nous avons reçu la livraison',
        workflow: 'Translation',
      });
      expect(stored().name).toBe('supply-memo.docx');

      await flush();
      expect(stored().name).toBe('French supply memo');
      expect(stored().nameAutoGenerated).toBe(true);
    });

    it('does not call the titler without a sample', () => {
      nameWorkflowConversation('w1', {
        label: 'Cholera Response Plan',
        workflow: 'Document',
      });
      expect(generateConversationTitle).not.toHaveBeenCalled();
    });

    it('does not clobber a rename made during the round trip', async () => {
      let resolveTitle: (value: unknown) => void = () => {};
      generateConversationTitle.mockReturnValue(
        new Promise((resolve) => {
          resolveTitle = resolve;
        }),
      );

      nameWorkflowConversation('w1', {
        sample: 'some source text',
        workflow: 'Translation',
      });

      // User renames while the title request is in flight.
      useConversationStore.getState().updateConversation('w1', {
        name: 'My own title',
        nameAutoGenerated: false,
      });
      resolveTitle({ title: 'Generated title', fullTitle: 'Generated title' });
      await flush();

      expect(stored().name).toBe('My own title');
    });

    it('calls the titler with synthetic entries only', () => {
      nameWorkflowConversation('w1', {
        sample: 'text',
        workflow: 'Map',
      });
      expect(generateConversationTitle).toHaveBeenCalledWith(expect.any(Array));
    });

    it('survives a titler rejection', async () => {
      generateConversationTitle.mockRejectedValue(new Error('boom'));
      vi.spyOn(console, 'error').mockImplementation(() => {});
      nameWorkflowConversation('w1', { sample: 'text', workflow: 'Map' });
      await flush();
      expect(stored().name).toBe('text');
    });
  });

  it('no-ops on an unknown conversation id', () => {
    nameWorkflowConversation('missing', { label: 'x', workflow: 'Map' });
    expect(stored().name).toBe('');
  });
});
